#!/usr/bin/perl
# Copyright (C) Eskild Hustvedt 2011
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# See http://www.placekitten.com/ for image license.
use strict;
use warnings;

foreach (@ARGV)
{
	my $w = $_;
	my $h = $_;
	$w =~ s/^(\d+)\D.+/$1/;
	$h =~ s/^\d+\D+(\d+)$/$1/;
	system('wget','-O','placekitty-'.$_.'.jpg','http://placekitten.com/g/'.$w.'/'.$h);
}
