#!/bin/bash
# Copyright (C) Eskild Hustvedt 2010
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
DIR="$1"
if [ ! -e "$DIR" ]; then
	echo "Usage: $0 [DIRECTORY]"
fi
for f in *; do
	TITLE="`id3info "$f"  |grep TIT2|perl -pi -e 's/.*\): //; s/\s*(\(LP\s*Version\)|Album Version)//gi'`"
	eyeD3 -t "$TITLE" "$f"
done
