#!/bin/bash
# Copyright (C) Eskild Hustvedt 2010
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
cd ~/.mozilla || cd ~/.mozilla-firefox || exit 1
for file in $(find -iname '*.sqlite'); do
	if type realpath &>/dev/null; then
		file="$(realpath "$file")"
	fi
	echo "VACUUMing $file"
	sqlite3 "$file" 'VACUUM;'
done
