#!/usr/bin/perl
# A script to convert cookies.txt files to a cookie format usable by phantomjs
# Copyright (C) Eskild Hustvedt 2012
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use 5.010;
use strict;
use warnings;

open(my $i,'<',shift(@ARGV)) or die;

my %cookies;

while($_ = <$i>)
{
    chomp($_);
    my @cookie = split(/\s+/,$_);
    my $domain = $cookie[0];
    $domain =~ s/^\.//;
    my $key = $cookie[5];
    my $value = $cookie[6];

    $cookies{$domain} //= {};
    $cookies{$domain}->{$key} = $value;
}

foreach my $domain (keys(%cookies))
{
    print '['.$domain.']'."\n";
    foreach my $key (keys (%{$cookies{$domain}}))
    {
        print $key.'='.$cookies{$domain}->{$key}."\n";
    }
    print "\n";
}
