#!/bin/bash
# Copyright (C) Eskild Hustvedt 2010
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
filenamecleaner *

extraarg='-type f'

if [ "$1" == "all" ]; then
	extraarg=""
fi

for file in `find -maxdepth 1 $extraarg -mtime +7`; do
	LSADD=""
	if [ -d "$file" ]; then
		LSADD="-d"
		if perl -e 'exit 1 if not $ARGV[0] =~ /^\d{4}$/' -- $(basename "$file"); then
			continue
		fi
	fi
	DATE="`ls $LSADD -l --time-style=long-iso "$file" | perl -pi -e 's#^\S+\s*\d+\s+\S+\s+\S+\s+\S+\s+##; s#\s*\d+:.*$##; s#-\d+$##;s#-#/#g;'`"
	# Alternate syntax
#	DATE="`ls $LSADD -l --time-style=long-iso "$file" | perl -pi -e 's#^\S+\s*\d+\s+\S+\s+\S+\s+\S+\s+##; s#\s*\d+:.*$##;'`"
	mkdir -v -p "$DATE"
	if [ -e "$DATE/$file" ]; then
		mv -v "$file" "$DATE/$file.$(date +%s)"
	else
		mv -v "$file" "$DATE/"
	fi
done
